[default]
# 【极致性能】禁用预览模式。因为你不跑图，设为 none 可以节省监听图片生成的资源。
preview_method = none

# 【加速安装】你刚才的日志显示已经安装了 uv，开启这个选项可以让安装节点快 10 倍，且占用内存极低。
use_uv = True

# 【网络优化】设为 private,告诉管理器只在本地回环地址工作，减少网络广播开销。
network_mode = private

# 【防止误触】设为 False。防止你在管理器里点错，导致浏览器试图下载几个 G 的真实模型把电脑卡死。
model_download_by_agent = False

# 【稳定优先】保持 stable，防止更新到测试版导致和云端环境不一致。
update_policy = stable-comfyui

# 【网络兼容】如果你的代理再次抽风导致报错，可以将下面这个改为 True，平时保持 False 安全些。
bypass_ssl = False

# 【其他默认项】
git_exe = 
channel_url = https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main
share_option = all
file_logging = True
component_policy = workflow
windows_selector_event_loop_policy = False
downgrade_blacklist = 
security_level = normal
always_lazy_install = False
db_mode = cache